import type { Metadata } from "next";
import StyledComponentsRegistry from "./registry";
import { GlobalStyle } from "@/theme/globalStyle";

export const metadata: Metadata = {
  title: "Events Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StyledComponentsRegistry>
      <html lang="en">
      <GlobalStyle />
        <body>{children}</body>
      </html>
    </StyledComponentsRegistry>
  );
}
