import type { Metadata } from "next";
import StyledComponentsRegistry from "./registry";
import { GlobalStyle } from "@/theme/globalStyle";
import { EventPlannerThemeProvider } from "@/theme";

export const metadata: Metadata = {
  title: "Events Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StyledComponentsRegistry>
      <EventPlannerThemeProvider>
        <html lang="en">
          <GlobalStyle />
          <body>{children}</body>
        </html>
      </EventPlannerThemeProvider>
    </StyledComponentsRegistry>
  );
}
